import { NextResponse } from "next/server";
import { db } from "@/lib/db";

/**
 * Serves the tailored resume HTML for an application so the user can preview it
 * and print to PDF from the browser (our MVP "export to PDF" path). The HTML is
 * generated by our renderer with escaped content — safe to serve as a document.
 */
export async function GET(_req: Request, { params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const version = await db.resumeVersion.findFirst({
    where: { applicationId: id },
    orderBy: { createdAt: "desc" },
  });
  if (!version?.htmlPreview) {
    return new NextResponse("No tailored resume found for this application.", { status: 404 });
  }
  return new NextResponse(version.htmlPreview, {
    headers: { "content-type": "text/html; charset=utf-8" },
  });
}
